### ISSUE TITLE
working example does not return content type json

### ISSUE THREAD

**Issue by Kissaki** [jpf/jsondns#1]
The working example at http://dig.jsondns.org/ serves JSON data for the requests perfectly,
but does not set the Content-Type HTTP header to _application/json_.

expected: HTTP response header Content-Type: application/json
current: HTTP response header Content-Type: text/plain

**Comment by jpf** [comment]
I explicitly send "Content-Type: text/plain" so that the JSON can be viewed in a web browser.

What is your use case? Perhaps I could send "Content-Type: application/json" if a specific query string parameter is set?

See also: http://news.ycombinator.com/item?id=1017633

**Comment by Kissaki** [comment]
I strongly object to using text/plain by default.
It’s just wrong.

For JSON data the mime type should be JSON, as, well, it’s json data.
Using a more generic type will not allow validating against type like (some?) JS frameworks do thus not being able to use it at all. Also, syntax-highlighting and further json-specific browser extension will not work.
Being able to view JSON is a browser issue and should not force functionally and semantically inferior methods.

As for IE, I’m not familiar with such issues, that it pops up save dialogs for AJAX loading of JSON data.
If it really does, again, why the heck should you work around such a stupidly non-standard browser by dropping important standard-elements like the mime-type?
It’s an IE issue then, not a library issue here.

For those obscure issues, a returntype option would be an alternative, although I strongly object on using text/plain as default. It is not the default case. JSON data is returned thus it should be described as such. (although one could argue returntype would be correct as it would still be JSON returned, just described as plain text … should one interpret plain text as JSON?)

**Comment by Kissaki** [comment]
This is not only for the example but for the lib as well, right?

**Comment by jpf** [comment]
I picked text/plain after a suggestion from a friend of mine who is an expert with DNS. That said, after reading the comments here: http://stackoverflow.com/questions/477816/the-right-json-content-type - I'm convinced that application/json should be the default.

Can you send a patch?

**Comment by Kissaki** [comment]
No, I didn’t patch anything (yet). :)
And if you want to delegate it to me it might take some time :P

**Comment by jpf** [comment]
Yeah, I was trying to delegate the task to you :D

I'll see what I can do over the weekend.
